steps:
  - task: Npm@1
    displayName: "\U0001F449 Package"
    inputs:
      command: custom
      customCommand: run package
      workingDir: $(working_directory)
    condition: succeeded()

  - task: MicroBuildSigningPlugin@4
    displayName: 'Install Signing Plugin'
    inputs:
      signType: 'Real'
      azureSubscription: 'MicroBuild Signing Task (DevDiv)'
    env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  # Cert 4014052 aka VSCodePublisher cert
  - script: |
      dotnet $MBSIGN_APPFOLDER/ddsignfiles.dll /file:$(Build.SourcesDirectory)/extension.vsix /certs:4014052
    displayName: Sign VSIX
    # condition: and(succeeded(), eq(variables['SigningType'], 'Real'))

  - task: CopyFiles@2
    displayName: "\U0001F449 Copy packages and vsix to staging directory"
    inputs:
      Contents: |
        **/*.vsix
        **/*.tar.gz
        **/*.tgz
      TargetFolder: "$(build.artifactstagingdirectory)/build/$(artifact_name)"
    condition: and(succeeded(), ne(variables['System.PullRequest.IsFork'], 'True'))
