steps:
  # put the extension name and version from the package.json into variables to use later. Variables can be used in later steps as $(package.name) and $(package.version)
  - pwsh: | 
      Write-Output "##vso[task.setvariable variable=name;isOutput=true]$((Get-Content -Raw -Path package.json | ConvertFrom-Json).name)"
      Write-Output "##vso[task.setvariable variable=version;isOutput=true]$((Get-Content -Raw -Path package.json | ConvertFrom-Json).version)"
    name: package
    displayName: "\U0001F449 Get extension info from package.json"

  - script: npx @vscode/vsce@latest generate-manifest -i $(package.name)-$(package.version).vsix -o $(Build.SourcesDirectory)/extension.manifest
    displayName: "\U0001F449 Generate extension manifest"

  - task: DotNetCoreCLI@2
    displayName: "\U0001F449 Sign with MSBuild"
    inputs:
      command: 'build'
      projects: 'SignExtension.signproj'