parameters:
  - name: "jobs"
    type: object
    default:
      - name: Root # TODO: would like this to be repository name but can't use build variables here
        working_directory: .
  - name: "useAzureFederatedCredentials"
    type: boolean
    default: true
  - name: "ENABLE_LONG_RUNNING_TESTS"
    type: boolean
    default: true

stages:
  - stage: BuildStage
    jobs:
      - ${{ each job in parameters.jobs }}:
          - job: ${{ job.name }}
            templateContext:
              outputs:
                - output: pipelineArtifact
                  targetPath: $(build.artifactstagingdirectory)/build/${{ job.name }}
                  artifactName: Build ${{ job.name }}
            steps:
              - template: ./templates/setup.yml
              - template: ./templates/build.yml
              - template: ./templates/1espackage.yml
              - template: ./templates/test.yml
                parameters:
                  useAzureFederatedCredentials: ${{ parameters.useAzureFederatedCredentials }}
                  ENABLE_LONG_RUNNING_TESTS: ${{ parameters.ENABLE_LONG_RUNNING_TESTS }}
            variables:
              artifact_name: ${{ job.name }}
              working_directory: ${{ job.working_directory }}
