parameters:
  - name: "jobs"
    type: object
    default:
      - name: Root # TODO: would like this to be repository name but can't use build variables here
        working_directory: .
  - name: "useAzureFederatedCredentials"
    type: boolean
    default: false

stages:
  - stage: BuildStage
    jobs:
      - ${{ each job in parameters.jobs }}:
          - job: ${{ job.name }}
            templateContext:
              mb: # Enable the MicroBuild Signing toolset
                signing:
                  enabled: true
                  signType: real # options are 'real' & 'test'
                  zipSources: false
              outputs:
                - output: pipelineArtifact
                  targetPath: $(build.artifactstagingdirectory)/build/${{ job.name }}
                  artifactName: Build ${{ job.name }}
            steps:
              - template: ./templates/setup.yml
              - template: ./templates/build.yml
              - template: ./templates/1espackage.yml

              # Check if the SignExtension.signproj file exists and set a variable using PowerShell
              - powershell: |
                  $filePath = "$(Build.SourcesDirectory)\SignExtension.signproj"
                  if (Test-Path $filePath) {
                      Write-Output "##vso[task.setvariable variable=signprojExists]true"
                      Write-Output "SignExtension.signproj file found. Signing extension."
                  } else {
                      Write-Output "##vso[task.setvariable variable=signprojExists]false"
                      Write-Output "SignExtension.signproj file not found. Skipping signing."
                  }
                name: CheckSignFile
                displayName: 'Check for SignExtension.signproj File'

              # Conditionally include the sign.yml template if the SignExtension.signproj file exists
              - ${{ if eq(variables['signprojExists'], 'true') }}:
                - template: ./templates/sign.yml

              - template: ./templates/stage-artifacts.yml
              - template: ./templates/test.yml
                parameters:
                  useAzureFederatedCredentials: ${{ parameters.useAzureFederatedCredentials }}
            variables:
              artifact_name: ${{ job.name }}
              working_directory: ${{ job.working_directory }}
